/* V12.6.9 — Smart Facebook Post Studio
   ชุด Facebook 5 ภาพ + ปกเดี่ยวเต็มภาพ + จัดภาพปกอิสระ + แคปชั่น AI
   ทำงานในเบราว์เซอร์ ไม่สร้างภาพใหม่ ไม่แก้ใบหน้า และไม่แต่งข้อมูลจริงเพิ่ม
*/
(function(){
  'use strict';
  const $=(q,root=document)=>root.querySelector(q);
  const $$=(q,root=document)=>Array.from(root.querySelectorAll(q));
  const state={files:[],coverId:null,coverMode:'double',logo:null,logoUrl:'',outputs:[],fullCover:null,caption:'',captionSource:'',facts:{},headlineX:50,headlineY:57,logoX:4,logoY:5,brandY:66,drag:null,refreshTimer:null,refreshSeq:0};
  const BRAND_STORAGE_KEY='tanjai_album_brand_v1';

  function clean(value){return String(value||'').replace(/\s+/g,' ').trim();}
  function cleanMultiline(value){return String(value||'').replace(/\r/g,'').split('\n').map(line=>line.replace(/[\t ]+/g,' ').trim()).filter(Boolean).join('\n').trim();}
  function esc(value){return String(value||'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));}
  function val(id,fallback=''){const el=document.getElementById(id);return el&&typeof el.value==='string'&&el.value.trim()?el.value.trim():fallback;}
  function num(id,fallback){const n=Number(val(id,String(fallback)));return Number.isFinite(n)?n:fallback;}
  function checked(id){return !!document.getElementById(id)?.checked;}
  function selectedCover(){return state.files.find(item=>item.id===state.coverId)||state.files[0]||null;}
  function supportingFiles(){const cover=selectedCover();return state.files.filter(item=>!cover||item.id!==cover.id);}
  function notify(message){if(window.TANJAI?.toast)TANJAI.toast(message);else alert(message);}
  function normalizeFacts(input={}){return{
    title:cleanMultiline(input.title),org:clean(input.org),date:clean(input.date),time:clean(input.time),place:clean(input.place),detail:clean(input.detail),footer:clean(input.footer),captionStyle:clean(input.captionStyle)||'official'
  };}
  function formData(){
    const facts=normalizeFacts({title:val('album-title',''),org:val('album-orgName',''),date:val('album-dateTime',''),time:val('album-time',''),place:val('album-place',''),detail:val('album-detail',''),footer:val('album-footer',''),captionStyle:val('album-captionStyle','official')});
    state.facts=facts;
    const bandStyle=val('album-bandStyle','template');
    return{...facts,coverStyle:val('album-coverStyle','official'),font:val('album-headlineFont','Kanit'),fontSize:num('album-headlineSize',88),fontWeight:num('album-headlineWeight',900),italic:checked('album-headlineItalic'),color:val('album-headlineColor','#f5c84c'),outlineColor:val('album-outlineColor','#24104f'),outlineWidth:num('album-outlineWidth',4),align:val('album-headlineAlign','center'),logoPosition:val('album-logoPosition','left'),logoSize:num('album-logoSize',10),shadow:checked('album-headlineShadow'),bandEnabled:bandStyle!=='none',bandColor:val('album-bandColor','#3b126b'),bandOpacity:82,bandStyle,bandAccentColor:val('album-headlineColor','#f5c84c'),bandAccentOpacity:52,bandAccentWidth:2,brandEnabled:checked('album-brandEnabled'),brandSlogan:val('album-brandSlogan',''),brandWebsite:val('album-brandWebsite',''),brandSocial:val('album-brandSocial',''),brandPhone:val('album-brandPhone','')};
  }
  function short(value,max=150){const text=clean(value);if(text.length<=max)return text;const cut=text.slice(0,max+1),at=Math.max(cut.lastIndexOf(' '),cut.lastIndexOf(' และ'),cut.lastIndexOf(' เพื่อ'));return(at>max*.55?cut.slice(0,at):cut.slice(0,max)).trim()+'…';}
  function rgba(hex,alpha){const raw=String(hex||'#24104f').replace('#',''),full=raw.length===3?raw.split('').map(x=>x+x).join(''):raw.padEnd(6,'0').slice(0,6);return`rgba(${parseInt(full.slice(0,2),16)},${parseInt(full.slice(2,4),16)},${parseInt(full.slice(4,6),16)},${alpha})`;}
  function revokeFiles(){state.files.forEach(item=>item.url&&URL.revokeObjectURL(item.url));}
  function revokeOutputs(){state.outputs.forEach(item=>item.url&&URL.revokeObjectURL(item.url));if(state.fullCover?.url)URL.revokeObjectURL(state.fullCover.url);state.outputs=[];state.fullCover=null;}
  function makeFileItem(file,index){return{file,id:`${Date.now()}-${index}-${Math.random().toString(36).slice(2)}`,url:URL.createObjectURL(file),cropX:50,cropY:50,zoom:1,coverX:0,coverY:0,coverZoom:1,coverFit:'fill'};}

  function ingestFiles(fileList){
    const valid=Array.from(fileList||[]).filter(file=>file.type.startsWith('image/'));if(!valid.length)return;
    revokeFiles();revokeOutputs();const limited=valid.slice(0,60);if(valid.length>60)notify('รองรับสูงสุด 60 ภาพ และเลือกใช้ 60 ภาพแรก');
    state.files=limited.map(makeFileItem);state.coverId=state.files[0]?.id||null;state.headlineX=50;state.headlineY=57;state.brandY=66;
    renderPhotoPicker();renderCoverEditor();renderCropList();renderEmptyResult();
  }
  async function loadLogo(file){
    if(state.logoUrl)URL.revokeObjectURL(state.logoUrl);state.logo=null;state.logoUrl='';
    if(!file){renderCoverEditor();scheduleGeneratedRefresh();return;}state.logoUrl=URL.createObjectURL(file);state.logo=await loadImage(state.logoUrl,false);renderCoverEditor();scheduleGeneratedRefresh();
  }
  function renderPhotoPicker(){
    const host=$('#album-photoPicker');if(!host)return;if(!state.files.length){host.hidden=true;host.innerHTML='';return;}host.hidden=false;
    host.innerHTML=`<div class="album-picker-head"><b>เลือกภาพที่จะใช้ทำปก</b><small>คลิกภาพหนึ่งใบ ภาพอื่นจะเป็นภาพกิจกรรมแบบไม่มีข้อความ</small></div><div class="album-picker-grid">${state.files.map((item,index)=>`<button type="button" class="album-picker-item${item.id===state.coverId?' selected':''}" data-cover-id="${item.id}"><img src="${item.url}" alt="ภาพที่ ${index+1}"><span>${item.id===state.coverId?'✓ ภาพปก':`ภาพที่ ${index+1}`}</span></button>`).join('')}</div>`;
  }
  function metaText(d){return[d.date,d.time,d.place].filter(Boolean).join(' · ');}
  function brandContacts(d){return[{icon:'◎',text:clean(d.brandWebsite)},{icon:'f',text:clean(d.brandSocial||d.org)},{icon:'☎',text:clean(d.brandPhone)}].filter(item=>item.text);}
  function hasBrandContent(d){return !!(clean(d.brandSlogan)||brandContacts(d).length);}
  function syncCoverControls(cover=selectedCover()){
    if(!cover)return;const values={"album-coverX":cover.coverX,"album-coverY":cover.coverY,"album-coverZoom":Math.round(cover.coverZoom*100)};
    Object.entries(values).forEach(([id,value])=>{const el=document.getElementById(id);if(el)el.value=value;});
    const labels={"album-coverXValue":Math.round(cover.coverX),"album-coverYValue":Math.round(cover.coverY),"album-coverZoomValue":`${Math.round(cover.coverZoom*100)}%`};
    Object.entries(labels).forEach(([id,value])=>{const el=document.getElementById(id);if(el)el.textContent=value;});
    $$('[data-photo-fit]').forEach(button=>button.classList.toggle('selected',button.dataset.photoFit===cover.coverFit));
  }
  function renderCoverEditor(){
    const host=$('#album-coverEditor');if(!host)return;const cover=selectedCover(),d=formData();
    if(!cover){host.className='album-cover-editor is-empty';host.innerHTML='<p>อัปโหลดภาพ แล้วเลือกภาพปกเพื่อเริ่มจัดวาง</p>';return;}
    host.className=`album-cover-editor mode-${state.coverMode}`;
    const isDouble=state.coverMode==='double',canvasW=2160,headlineSize=headlineFontSize(d.title,d.fontSize,true),headlineSourceSize=headlineSize*1.28,previewHeadlineSize=headlineSourceSize/canvasW*100,previewOutlineSize=d.outlineWidth*1.35/canvasW*100;
    const styleClass=`style-${d.coverStyle}`,showBrand=d.coverStyle==='official'&&d.brandEnabled&&hasBrandContent(d),contacts=brandContacts(d),accentAlpha=Math.max(.1,Math.min(1,d.bandAccentOpacity/100));
    const logoHtml=(state.logoUrl&&d.logoPosition!=='none')?`<img id="albumLogoDrag" class="album-editor-logo" src="${state.logoUrl}" alt="โลโก้จริง" style="left:${state.logoX}%;top:${state.logoY}%;width:${d.logoSize}%">`:'';
    const dividerColor=d.bandStyle==='template'?d.bandAccentColor:'#ffffff',dividerAlpha=d.bandStyle==='template'?accentAlpha:.72;
    const brandHtml=showBrand?`<div id="albumBrandDrag" class="album-brand-drag band-${d.bandStyle}" style="top:${state.brandY}%;--album-accent:${rgba(dividerColor,dividerAlpha)}"><i></i>${d.brandSlogan?`<b>${esc(d.brandSlogan)}</b>`:''}<div>${contacts.map(item=>`<span><em>${esc(item.icon)}</em>${esc(item.text)}</span>`).join('')}</div></div>`:'';
    const photoStyle=`left:${50+cover.coverX}%;top:${50+cover.coverY}%;transform:translate(-50%,-50%) scale(${cover.coverZoom});object-fit:${cover.coverFit==='contain'?'contain':'cover'}`;
    const bandStyle=`background:linear-gradient(180deg,${rgba(d.bandColor,0)} 0%,${rgba(d.bandColor,Math.max(.18,d.bandOpacity/100*.72))} 28%,${rgba(d.bandColor,d.bandOpacity/100)} 100%);display:${d.bandEnabled?'block':'none'}`;
    const decorHtml=d.bandStyle==='template'?`<div class="album-band-decor style-template" style="--album-accent:${rgba(d.bandAccentColor,accentAlpha)};--album-accent-soft:${rgba(d.bandAccentColor,accentAlpha*.22)}"><i class="curve-left"></i><i class="curve-right"></i></div>`:'';
    host.innerHTML=`<div class="album-cover-stage ${styleClass}" id="albumCoverStage"><img class="album-editor-photo-bg" src="${cover.url}" alt="" aria-hidden="true"><img id="albumPhotoDrag" class="album-editor-photo" src="${cover.url}" alt="ภาพปก" style="${photoStyle}"><div class="album-editor-shade"></div><div class="album-editor-band" style="${bandStyle}"></div>${decorHtml}${isDouble?'<i class="album-editor-seam" aria-hidden="true"></i>':''}${logoHtml}<div id="albumHeadlineDrag" class="album-headline-drag align-${d.align}${d.italic?' is-italic':''}" style="left:${state.headlineX}%;top:${state.headlineY}%;font-family:'${esc(d.font)}',sans-serif;font-size:${previewHeadlineSize}cqw;font-weight:${d.fontWeight};color:${d.color};-webkit-text-stroke:${previewOutlineSize}cqw ${d.outlineColor};text-shadow:${d.shadow?'0 3px 10px rgba(0,0,0,.72)':'none'}">${esc(d.title||'ข้อความพาดหัว').replace(/\n/g,'<br>')}</div>${brandHtml}</div>`;
    syncCoverControls(cover);bindStageDrag();renderWarning();
  }
  function renderWarning(){
    const host=$('#album-coverWarning');if(!host)return;const d=formData(),warnings=[];
    if(d.title.length>90)warnings.push('พาดหัวยาว อาจอ่านไม่ทันบนมือถือ');
    if(state.coverMode==='double'&&state.headlineX>43&&state.headlineX<57&&d.title.length>34)warnings.push('พาดหัวอยู่ใกล้รอยต่อกลาง กรุณาตรวจว่าไม่มีตัวอักษรถูกแบ่งครึ่ง');
    if(!d.title)warnings.push('ยังไม่ได้ใส่ข้อความพาดหัว');host.hidden=!warnings.length;host.textContent=warnings.join(' · ');
  }
  function bindStageDrag(){
    const stage=$('#albumCoverStage');if(!stage)return;
    [['#albumPhotoDrag','photo'],['#albumHeadlineDrag','headline'],['#albumLogoDrag','logo'],['#albumBrandDrag','brand']].forEach(([selector,type])=>{const drag=$(selector);if(!drag)return;
      drag.addEventListener('pointerdown',event=>{event.preventDefault();drag.setPointerCapture?.(event.pointerId);const cover=selectedCover();state.drag={stage,type,startX:event.clientX,startY:event.clientY,coverX:cover?.coverX||0,coverY:cover?.coverY||0};drag.classList.add('dragging');});
      drag.addEventListener('pointermove',event=>{if(state.drag?.type!==type)return;const rect=stage.getBoundingClientRect(),x=((event.clientX-rect.left)/rect.width)*100,y=((event.clientY-rect.top)/rect.height)*100;if(type==='photo'){const cover=selectedCover();if(!cover)return;cover.coverX=Math.max(-50,Math.min(50,state.drag.coverX+(event.clientX-state.drag.startX)/rect.width*100));cover.coverY=Math.max(-50,Math.min(50,state.drag.coverY+(event.clientY-state.drag.startY)/rect.height*100));drag.style.left=(50+cover.coverX)+'%';drag.style.top=(50+cover.coverY)+'%';syncCoverControls(cover);}else if(type==='headline'){state.headlineX=Math.max(8,Math.min(92,x));state.headlineY=Math.max(12,Math.min(69,y));drag.style.left=state.headlineX+'%';drag.style.top=state.headlineY+'%';renderWarning();}else if(type==='brand'){state.brandY=Math.max(62,Math.min(82,y));drag.style.top=state.brandY+'%';}else{const size=formData().logoSize;state.logoX=Math.max(1,Math.min(99-size,x));state.logoY=Math.max(1,Math.min(82,y));drag.style.left=state.logoX+'%';drag.style.top=state.logoY+'%';}});
      const stop=()=>{if(state.drag?.type===type)scheduleGeneratedRefresh();state.drag=null;drag.classList.remove('dragging');};drag.addEventListener('pointerup',stop);drag.addEventListener('pointercancel',stop);
    });
  }
  function renderCropList(){
    const host=$('#album-cropList');if(!host)return;const supports=supportingFiles();
    if(!state.files.length){host.innerHTML='<div class="album-empty-note">อัปโหลดภาพกิจกรรมก่อน</div>';return;}
    if(!supports.length){host.innerHTML='<div class="album-empty-note">มีเพียงภาพปก ยังไม่มีภาพกิจกรรมเพิ่มเติม</div>';return;}
    host.innerHTML=supports.map((item,index)=>`<article class="album-crop-card" data-file-id="${item.id}"><div class="album-crop-thumb"><img src="${item.url}" alt="ภาพกิจกรรม ${index+1}" style="object-position:${item.cropX}% ${item.cropY}%;transform:scale(${item.zoom})"></div><div class="album-crop-controls"><div><b>ภาพกิจกรรม ${index+1}</b><small>${esc(item.file.name)}</small></div><label>ซ้าย–ขวา<input type="range" min="0" max="100" value="${item.cropX}" data-crop-axis="x"></label><label>บน–ล่าง<input type="range" min="0" max="100" value="${item.cropY}" data-crop-axis="y"></label><label>ขยาย<input type="range" min="100" max="180" value="${Math.round(item.zoom*100)}" data-crop-axis="zoom"></label><div class="album-order-actions"><button type="button" data-move="up" ${index===0?'disabled':''}>← ก่อนหน้า</button><button type="button" data-move="down" ${index===supports.length-1?'disabled':''}>ถัดไป →</button></div></div></article>`).join('');
  }
  function updateCrop(input){
    const card=input.closest('[data-file-id]'),item=state.files.find(file=>file.id===card?.dataset.fileId);if(!item)return;const axis=input.dataset.cropAxis,value=Number(input.value);
    if(axis==='x')item.cropX=value;else if(axis==='y')item.cropY=value;else item.zoom=value/100;const img=card.querySelector('img');if(img){img.style.objectPosition=`${item.cropX}% ${item.cropY}%`;img.style.transform=`scale(${item.zoom})`;}
  }
  function moveSupport(id,direction){
    const cover=selectedCover(),supports=supportingFiles(),at=supports.findIndex(item=>item.id===id),to=direction==='up'?at-1:at+1;if(at<0||to<0||to>=supports.length)return;
    [supports[at],supports[to]]=[supports[to],supports[at]];state.files=cover?[cover,...supports]:supports;renderPhotoPicker();renderCropList();
  }

  function loadImage(source,revoke=true){return new Promise((resolve,reject)=>{const img=new Image(),url=typeof source==='string'?source:URL.createObjectURL(source);img.onload=()=>{if(revoke&&typeof source!=='string')URL.revokeObjectURL(url);resolve(img);};img.onerror=error=>{if(revoke&&typeof source!=='string')URL.revokeObjectURL(url);reject(error);};img.src=url;});}
  function cropPlacement(sw,sh,w,h,xPct=50,yPct=50,zoom=1){const base=Math.max(w/sw,h/sh),scale=base*Math.max(1,zoom),nw=sw*scale,nh=sh*scale;return{scale,nw,nh,x:(w-nw)*(Math.max(0,Math.min(100,xPct))/100),y:(h-nh)*(Math.max(0,Math.min(100,yPct))/100)};}
  function drawCrop(ctx,img,w,h,item){const p=cropPlacement(img.naturalWidth||img.width,img.naturalHeight||img.height,w,h,item.cropX,item.cropY,item.zoom);ctx.drawImage(img,p.x,p.y,p.nw,p.nh);}
  function coverPlacement(sw,sh,w,h,item={}){const fit=item.coverFit==='contain'?'contain':'fill',base=(fit==='contain'?Math.min:Math.max)(w/sw,h/sh),scale=base*Math.max(.5,Math.min(2.5,Number(item.coverZoom)||1)),nw=sw*scale,nh=sh*scale,x=(w-nw)/2+(Number(item.coverX)||0)/100*w,y=(h-nh)/2+(Number(item.coverY)||0)/100*h;return{fit,scale,nw,nh,x,y};}
  function drawCoverPhoto(ctx,img,w,h,item){if(item.coverFit==='contain'){ctx.save();ctx.filter='blur(34px) brightness(.58)';drawCrop(ctx,img,w,h,{cropX:50,cropY:50,zoom:1.08});ctx.restore();ctx.fillStyle='rgba(4,6,16,.18)';ctx.fillRect(0,0,w,h);}const p=coverPlacement(img.naturalWidth||img.width,img.naturalHeight||img.height,w,h,item);ctx.drawImage(img,p.x,p.y,p.nw,p.nh);}
  function textTokens(text){try{return Array.from(new Intl.Segmenter('th',{granularity:'word'}).segment(text)).map(x=>x.segment).filter(Boolean);}catch(_){return String(text).split(/(\s+)/).filter(Boolean);}}
  function wrapAllLines(ctx,text,maxWidth){const tokens=textTokens(clean(text)),lines=[];let line='';tokens.forEach(token=>{const trial=line+token;if(line&&ctx.measureText(trial).width>maxWidth){lines.push(line.trim());line=token;}else line=trial;});if(line.trim())lines.push(line.trim());return lines;}
  function wrapHeadlineLines(ctx,text,maxWidth){const manual=cleanMultiline(text).split('\n').filter(Boolean),lines=[];(manual.length?manual:['']).forEach(line=>lines.push(...wrapAllLines(ctx,line,maxWidth)));return lines.length?lines:[''];}
  function wrapLines(ctx,text,maxWidth,maxLines){const lines=wrapAllLines(ctx,text,maxWidth);if(lines.length<=maxLines)return lines;const out=lines.slice(0,maxLines);let last=out[maxLines-1];while(last.length>1&&ctx.measureText(last+'…').width>maxWidth)last=last.slice(0,-1);out[maxLines-1]=last.trim()+'…';return out;}
  function fitDetailLines(ctx,text,maxWidth,maxLines,startSize,minSize=8){let size=startSize,lines=[];while(size>=minSize){ctx.font=`600 ${size}px "Sarabun","Noto Sans Thai",sans-serif`;lines=wrapAllLines(ctx,text,maxWidth);if(lines.length<=maxLines)return{size,lines};size--;}return{size:minSize,lines:wrapAllLines(ctx,text,maxWidth)};}
  function headlineFontSize(text,base,isDouble=true){const length=clean(text).length,ratio=isDouble?(length>110?.68:length>80?.78:length>55?.88:1):(length>110?.55:length>80?.67:length>55?.8:1);return Math.max(34,Math.round(base*ratio));}
  function drawHeadline(ctx,w,h,d){
    const text=d.title||'ข้อความพาดหัว',size=headlineFontSize(text,d.fontSize,w===2160)*(w===2160?1.28:1),italic=d.italic?'italic ':'';ctx.save();ctx.font=`${italic}${d.fontWeight} ${Math.round(size)}px "${d.font}","Noto Sans Thai",sans-serif`;ctx.textBaseline='middle';ctx.textAlign=d.align;
    const maxWidth=w*.82,lines=wrapHeadlineLines(ctx,text,maxWidth),lineH=size*1.13,x=w*(state.headlineX/100),centerY=h*(state.headlineY/100),startY=centerY-((lines.length-1)*lineH)/2;ctx.lineJoin='round';ctx.miterLimit=2;
    if(d.shadow){ctx.shadowColor='rgba(0,0,0,.72)';ctx.shadowBlur=Math.max(10,size*.18);ctx.shadowOffsetY=Math.max(3,size*.06);}
    lines.forEach((line,index)=>{let drawX=x;if(d.align==='left')drawX=Math.max(w*.06,x-maxWidth/2);if(d.align==='right')drawX=Math.min(w*.94,x+maxWidth/2);if(d.outlineWidth>0){ctx.lineWidth=d.outlineWidth*(w===2160?1.35:1);ctx.strokeStyle=d.outlineColor;ctx.strokeText(line,drawX,startY+index*lineH,maxWidth);}ctx.fillStyle=d.color;ctx.fillText(line,drawX,startY+index*lineH,maxWidth);});ctx.restore();
  }
  function drawContained(ctx,img,x,y,maxW,maxH){const iw=img.naturalWidth||img.width,ih=img.naturalHeight||img.height,scale=Math.min(maxW/iw,maxH/ih),w=iw*scale,h=ih*scale;ctx.drawImage(img,x+(maxW-w)/2,y+(maxH-h)/2,w,h);}
  function drawBrandFooter(ctx,w,h,d){
    if(d.coverStyle!=='official'||!d.brandEnabled||!hasBrandContent(d))return;const contacts=brandContacts(d),isDouble=w===2160,y=h*(state.brandY/100),accent=d.bandStyle==='template'?d.bandAccentColor:'#ffffff',accentOpacity=d.bandStyle==='template'?d.bandAccentOpacity/100:.72;ctx.save();ctx.textAlign='center';ctx.textBaseline='middle';const line=ctx.createLinearGradient(w*.18,0,w*.82,0);line.addColorStop(0,rgba(accent,0));line.addColorStop(.16,rgba(accent,accentOpacity*.72));line.addColorStop(.5,rgba(accent,accentOpacity));line.addColorStop(.84,rgba(accent,accentOpacity*.72));line.addColorStop(1,rgba(accent,0));ctx.fillStyle=line;ctx.fillRect(w*.18,y,w*.64,2);if(d.bandStyle==='template'){ctx.globalAlpha=.34;ctx.fillRect(w*.23,y+8,w*.54,1);ctx.globalAlpha=1;}
    let cursor=y+64;if(d.brandSlogan){const sloganSize=isDouble?42:28;ctx.font=`800 ${sloganSize}px "Kanit","Noto Sans Thai",sans-serif`;ctx.fillStyle=d.color||'#f5c84c';ctx.shadowColor='rgba(0,0,0,.58)';ctx.shadowBlur=8;ctx.fillText(clean(d.brandSlogan),w/2,cursor,w*.82);cursor+=isDouble?78:66;}
    if(contacts.length){let size=isDouble?29:22,gap=isDouble?60:24;const labels=contacts.map(item=>`${item.icon}  ${item.text}`);while(size>14){ctx.font=`600 ${size}px "Sarabun","Noto Sans Thai",sans-serif`;const total=labels.reduce((sum,label)=>sum+ctx.measureText(label).width,0)+gap*(labels.length-1);if(total<=w*.84)break;size-=1;}ctx.font=`600 ${size}px "Sarabun","Noto Sans Thai",sans-serif`;ctx.fillStyle='#fff';const widths=labels.map(label=>ctx.measureText(label).width),total=widths.reduce((sum,value)=>sum+value,0)+gap*(labels.length-1);let x=(w-total)/2;labels.forEach((label,index)=>{ctx.textAlign='left';ctx.fillText(label,x,cursor);x+=widths[index]+gap;});}
    ctx.restore();
  }
  function drawBandDecor(ctx,w,h,d){
    if(d.bandStyle!=='template')return;const alpha=.26;
    ctx.save();ctx.strokeStyle=rgba(d.bandAccentColor,alpha);ctx.lineWidth=1.5;ctx.shadowColor=rgba(d.bandAccentColor,.18);ctx.shadowBlur=8;ctx.beginPath();ctx.moveTo(0,h*.88);ctx.bezierCurveTo(w*.07,h*.95,w*.13,h*.92,w*.23,h);ctx.stroke();ctx.beginPath();ctx.moveTo(w,h*.88);ctx.bezierCurveTo(w*.93,h*.95,w*.87,h*.92,w*.77,h);ctx.stroke();
    ctx.restore();
  }
  function drawCoverOverlays(ctx,w,h,d){
    const shade=ctx.createLinearGradient(0,0,0,h);shade.addColorStop(0,'rgba(0,0,0,.16)');shade.addColorStop(.5,'rgba(0,0,0,.02)');shade.addColorStop(1,d.coverStyle==='minimal'?'rgba(0,0,0,.08)':'rgba(0,0,0,.34)');ctx.fillStyle=shade;ctx.fillRect(0,0,w,h);
    if(d.bandEnabled){const band=ctx.createLinearGradient(0,h*.5,0,h);band.addColorStop(0,rgba(d.bandColor,0));band.addColorStop(.28,rgba(d.bandColor,Math.max(.18,d.bandOpacity/100*.72)));band.addColorStop(1,rgba(d.bandColor,d.bandOpacity/100));ctx.fillStyle=band;ctx.fillRect(0,h*.5,w,h*.5);drawBandDecor(ctx,w,h,d);}
    if(state.logo&&d.logoPosition!=='none'){const box=w*(d.logoSize/100),x=w*(state.logoX/100),y=h*(state.logoY/100);ctx.save();ctx.shadowColor='rgba(0,0,0,.5)';ctx.shadowBlur=18;drawContained(ctx,state.logo,x,y,box,box);ctx.restore();}drawHeadline(ctx,w,h,d);drawBrandFooter(ctx,w,h,d);
  }
  function canvasBlob(canvas,type='image/jpeg',quality=.93){return new Promise(resolve=>canvas.toBlob(resolve,type,quality));}
  async function buildCover(){
    const cover=selectedCover(),d=formData();if(!cover)return[];const W=2160,H=1080,canvas=document.createElement('canvas');canvas.width=W;canvas.height=H;const ctx=canvas.getContext('2d'),img=await loadImage(cover.file);drawCoverPhoto(ctx,img,W,H,cover);drawCoverOverlays(ctx,W,H,d);const fullBlob=await canvasBlob(canvas);state.fullCover={blob:fullBlob,url:URL.createObjectURL(fullBlob),role:'full-cover',filename:'cover-full-2160x1080.jpg',w:2160,h:1080};
    if(state.coverMode==='single')return[{blob:fullBlob,url:URL.createObjectURL(fullBlob),role:'cover',filename:'01-cover-full.jpg',w:2160,h:1080}];
    const outs=[];for(let i=0;i<2;i++){const half=document.createElement('canvas');half.width=1080;half.height=1080;half.getContext('2d').drawImage(canvas,i*1080,0,1080,1080,0,0,1080,1080);const blob=await canvasBlob(half);outs.push({blob,url:URL.createObjectURL(blob),role:'cover',filename:`0${i+1}-cover-${i?'right':'left'}.jpg`,w:1080,h:1080});}return outs;
  }
  async function buildSupport(item,index,offset){const canvas=document.createElement('canvas');canvas.width=1080;canvas.height=1080;const ctx=canvas.getContext('2d'),img=await loadImage(item.file);drawCrop(ctx,img,1080,1080,item);const blob=await canvasBlob(canvas),number=String(index+offset).padStart(2,'0');return{blob,url:URL.createObjectURL(blob),role:'photo',filename:`${number}-photo.jpg`,w:1080,h:1080};}

  function scheduleGeneratedRefresh(){
    if(!state.outputs.length)return;clearTimeout(state.refreshTimer);const seq=++state.refreshSeq;
    state.refreshTimer=setTimeout(async()=>{try{const oldFull=state.fullCover?.url||'',covers=await buildCover();if(seq!==state.refreshSeq){covers.forEach(item=>URL.revokeObjectURL(item.url));if(state.fullCover?.url)URL.revokeObjectURL(state.fullCover.url);state.fullCover=null;return;}if(oldFull)URL.revokeObjectURL(oldFull);let photos=[];if(state.coverMode==='double'){photos=state.outputs.filter(item=>item.role==='photo');if(!photos.length){const supports=supportingFiles(),offset=covers.length+1;for(let i=0;i<supports.length;i++)photos.push(await buildSupport(supports[i],i,offset));}}const replaced=state.outputs.filter(item=>item.role==='cover'||(state.coverMode==='single'&&item.role==='photo'));replaced.forEach(item=>URL.revokeObjectURL(item.url));state.outputs=[...covers,...photos];renderOutputs();}catch(error){console.error(error);}},280);
  }

  function factGuardCaption(text){return String(text||'').split('\n').map(line=>line.trimEnd()).filter(line=>line&&!/undefined|null|placeholder|กรอกข้อมูล|กรุณาเติม|ไม่ระบุข้อมูล/i.test(line)).join('\n').replace(/\n{3,}/g,'\n\n').trim();}
  function captionWriter(d,style=d.captionStyle||'official'){
    const title=clean(d.title),org=clean(d.org),detail=clean(d.detail),footer=clean(d.footer),blocks=[],icon=style==='friendly'?'✨':style==='story'?'📷':style==='announcement'?'📣':'🎯';if(title)blocks.push(`${icon} ${title}`);
    const meta=[d.date&&`📅 ${d.date}${d.time?' '+d.time:''}`,d.place&&`📍 ${d.place}`].filter(Boolean).join('\n');if(meta)blocks.push(meta);
    const detailParts=detail.split(/(?:\n+|(?<=[.!?])\s+)/).map(clean).filter(Boolean),body=[];if(org)body.push(org);if(detailParts.length)body.push(detailParts.join('\n\n'));if(body.length)blocks.push(body.join(' '));if(footer)blocks.push(footer);return factGuardCaption(blocks.join('\n\n'));
  }
  async function generateSmartCaption(d,button=null){
    const fallback=()=>captionWriter(d,d.captionStyle),facts=[d.title,d.org,d.date,d.time,d.place,d.detail,d.footer].filter(Boolean).join('\n');
    if(!window.TANJAI?.generateWritingWithAI){state.captionSource='เรียบเรียงในเครื่อง';return fallback();}
    const result=await TANJAI.generateWritingWithAI({
      tool:'post',button,
      data:{title:clean(d.title),organization:d.org,date:d.date,time:d.time,place:d.place,detail:d.detail,footer:d.footer,lockedFacts:facts,_postStrict:true},
      options:{channel:'โพสต์ Facebook พร้อมเผยแพร่',platform:'Facebook',purpose:'สรุปกิจกรรมและประชาสัมพันธ์',delivery:'ข่าวประชาสัมพันธ์ที่เป็นธรรมชาติ อ่านง่าย',creativity:'ช่วยคิดและแต่งให้สมบูรณ์',emoji:'ใช้เท่าที่จำเป็น',hashtags:'สร้าง 2–4 แฮชแท็กจากข้อมูลจริง',captionStyle:d.captionStyle,silentStatus:true,extra:'เขียนแคปชั่นฉบับพร้อมโพสต์ให้มีเนื้อหา ไม่ใช่เพียงนำช่องข้อมูลมาต่อกัน เริ่มด้วยพาดหัว ตามด้วยวัน เวลา สถานที่ แล้วเรียบเรียงว่าใครทำอะไร ผู้เกี่ยวข้อง ประเด็นสำคัญ และผลที่เกิดขึ้นตามข้อมูลจริง ใช้ย่อหน้าและคำเชื่อมที่เป็นธรรมชาติ เติมได้เฉพาะบริบทหรือประโยชน์ทั่วไปที่อนุมานอย่างปลอดภัยจากกิจกรรมนั้น ปิดท้ายและใส่แฮชแท็ก 2–4 แท็ก ส่งเฉพาะแคปชั่น ห้ามสร้างชื่อบุคคล ตำแหน่ง วัน เวลา สถานที่ ตัวเลข มติ ผลงาน หรือผลลัพธ์ที่ผู้ใช้ไม่ได้ให้'},
      fallback
    });
    window.TANJAI_AUTH?.trackUsage?.('album_caption');
    state.captionSource=result?.source==='fallback'?'เรียบเรียงในเครื่อง':'AI เรียบเรียง';
    return factGuardCaption(result?.text)||fallback();
  }
  function progress(show,label='กำลังสร้างชุดภาพ...',percent=0){let box=$('#albumProgress');if(!box){box=document.createElement('div');box.id='albumProgress';box.className='album-progress-bar-wrap';box.innerHTML='<div class="album-progress-bar" id="albumProgressInner"></div><small id="albumProgressLabel"></small>';$('#albumResult')?.prepend(box);}box.style.display=show?'block':'none';const bar=$('#albumProgressInner'),text=$('#albumProgressLabel');if(bar)bar.style.width=percent+'%';if(text)text.textContent=label;}
  async function generate(){
    const d=formData(),cover=selectedCover(),supports=supportingFiles();if(!cover)return notify('กรุณาอัปโหลดและเลือกภาพปก');if(!d.title)return notify('กรุณาใส่ข้อความพาดหัวบนภาพปก');if(state.coverMode==='double'&&supports.length<3)return notify('ชุด Facebook ต้องมีภาพปก 1 ภาพ และภาพกิจกรรมอย่างน้อย 3 ภาพ');revokeOutputs();const btn=$('#makeAlbum'),old=btn?.textContent;if(btn){btn.disabled=true;btn.textContent='กำลังสร้าง...';}
    try{if(document.fonts?.ready)await document.fonts.ready;progress(true,'กำลังสร้างภาพปก...',8);state.outputs.push(...await buildCover());if(state.coverMode==='double'){const offset=state.outputs.length+1;for(let i=0;i<supports.length;i++){progress(true,`กำลังครอปภาพกิจกรรม ${i+1}/${supports.length}...`,Math.round(10+((i+1)/Math.max(1,supports.length))*72));state.outputs.push(await buildSupport(supports[i],i,offset));}}progress(true,'AI กำลังเรียบเรียงแคปชั่นจากข้อมูลจริง...',88);state.caption=await generateSmartCaption(d);progress(true,'กำลังจัดตัวอย่าง Facebook...',96);renderOutputs();progress(true,'เสร็จแล้ว ✓',100);setTimeout(()=>progress(false),1200);}catch(error){console.error(error);notify('สร้างภาพไม่สำเร็จ กรุณาตรวจไฟล์แล้วลองใหม่');progress(false);}finally{if(btn){btn.disabled=false;btn.textContent=old||'สร้างภาพและแคปชั่นด้วย AI';}}
  }

  function previewCells(){const visible=state.outputs.slice(0,5),total=state.outputs.length;return visible.map((item,index)=>`<div class="fb-five-cell cell-${index+1}"><img src="${item.url}" alt="ภาพที่ ${index+1}">${index===4&&total>5?`<span class="fb-preview-more">+${total-5}</span>`:''}</div>`).join('');}
  function renderFacebookPreview(){const host=$('#albumFacebookPreview');if(!host)return;const d=formData(),caption=$('#albumCaptionText')?.value||state.caption,isSingle=state.coverMode==='single';host.innerHTML=`<div class="fb-preview-card"><div class="fb-preview-head"><div class="fb-preview-avatar">${state.logoUrl?`<img src="${state.logoUrl}" alt="">`:'เพจ'}</div><div><div class="fb-preview-name">${esc(d.org||'ชื่อเพจของคุณ')}</div><div class="fb-preview-time">เมื่อสักครู่ · 🌐</div></div></div><div class="fb-preview-caption">${esc(caption).replace(/\n/g,'<br>')}</div><div class="fb-five-grid count-${Math.min(5,state.outputs.length)}${isSingle?' single-cover':''}">${previewCells()}</div><div class="fb-preview-foot">${isSingle?'ตัวอย่างโพสต์ปกเดี่ยวแบบไม่ตัดแบ่ง':`ตัวอย่างชุด Facebook · ปก 2 ภาพบน + 3 ภาพล่าง${state.outputs.length>5?` · ภาพที่ 5 แสดง +${state.outputs.length-5}`:''}`}</div></div>`;}
  function renderOutputs(){
    const host=$('#albumResult .ready-main')||$('#albumResult');if(!host)return;const isSingle=state.coverMode==='single',size=isSingle?'2160 × 1080':'1080 × 1080';host.innerHTML=`<div class="album-pro-panel"><section class="album-preview-section album-post-first"><div class="album-preview-title"><div><b>ตัวอย่างโพสต์ Facebook</b><p>${isSingle?'ปกเต็มหนึ่งภาพ ไม่มีรอยต่อกลาง':'ตรวจลำดับและรอยต่อของปก 2 ภาพก่อนอัปโหลดตามหมายเลข'}</p></div><span class="album-ready-badge">${state.outputs.length} ภาพ · ${size}</span></div><div class="album-post-actions"><button class="btn primary" id="albumCopyCaptionQuick">คัดลอกแคปชั่น</button><button class="btn secondary" id="albumDownloadAllResult">${isSingle?'ดาวน์โหลดปกเดี่ยว':'ดาวน์โหลดชุด Facebook ZIP'}</button>${!isSingle&&state.fullCover?'<button class="btn secondary" id="albumDownloadCoverResult">ดาวน์โหลดปกเต็มไม่ตัด</button>':''}</div><div id="albumFacebookPreview"></div></section><details class="album-review-details album-caption-edit-details" open><summary><span><b>แคปชั่นพร้อมโพสต์</b><small>${esc(state.captionSource||'เรียบเรียงจากข้อมูลจริง')} · แก้ไขได้ก่อนคัดลอก</small></span></summary><div class="album-caption-box"><textarea id="albumCaptionText" rows="12">${esc(state.caption)}</textarea><div class="album-caption-actions"><button class="btn primary" id="albumCopyCaption">คัดลอกแคปชั่น</button><button class="btn secondary" id="albumRegenerateCaptionAI">✨ AI เพิ่มเนื้อหาและเขียนใหม่</button><button class="btn secondary" id="albumRefreshPreview">อัปเดตตัวอย่าง</button><button class="btn secondary" id="albumSaveProject">💾 บันทึกงาน</button></div></div></details><details class="album-review-details"><summary><span><b>ตรวจและดาวน์โหลดภาพรายใบ</b><small>${isSingle?'ภาพปกเต็มพร้อมใช้งาน':'สองภาพแรกคือปกต่อกัน ภาพถัดไปเป็นภาพกิจกรรมครอปสะอาด'}</small></span></summary><div class="album-output-grid">${state.outputs.map((item,index)=>`<article><img src="${item.url}" alt="ภาพที่ ${index+1}"><b>${esc(item.filename)}</b><button class="btn secondary album-one-download" data-index="${index}">ดาวน์โหลด</button></article>`).join('')}</div></details></div>`;renderFacebookPreview();
  }
  function renderEmptyResult(){const host=$('#albumResult .ready-main')||$('#albumResult');if(host&&state.outputs.length===0)host.innerHTML='<div class="ready-empty"><b>ชุดภาพจะแสดงที่นี่</b><span>เลือกภาพปก จัดข้อความและจุดครอป แล้วกดสร้างชุดภาพ</span></div>';}

  const encoder=new TextEncoder();let crcTable=null;
  function crc32(buf){if(!crcTable)crcTable=Array.from({length:256},(_,n)=>{let c=n;for(let i=0;i<8;i++)c=(c&1)?0xEDB88320^(c>>>1):c>>>1;return c>>>0;});let c=0xffffffff;for(const b of buf)c=crcTable[(c^b)&255]^(c>>>8);return(c^0xffffffff)>>>0;}
  const u16=n=>[n&255,(n>>>8)&255],u32=n=>[n&255,(n>>>8)&255,(n>>>16)&255,(n>>>24)&255];
  function dosDateTime(date=new Date()){return{time:(date.getHours()<<11)|(date.getMinutes()<<5)|Math.floor(date.getSeconds()/2),day:((date.getFullYear()-1980)<<9)|((date.getMonth()+1)<<5)|date.getDate()};}
  async function makeZip(entries){const chunks=[],central=[];let offset=0;const dt=dosDateTime();for(const entry of entries){const bytes=new Uint8Array(await entry.blob.arrayBuffer()),name=encoder.encode(entry.filename),crc=crc32(bytes),size=bytes.length,local=new Uint8Array([...u32(0x04034b50),...u16(20),...u16(0),...u16(0),...u16(dt.time),...u16(dt.day),...u32(crc),...u32(size),...u32(size),...u16(name.length),...u16(0),...name]);chunks.push(local,bytes);central.push({name,crc,size,offset});offset+=local.length+bytes.length;}const start=offset,parts=[];for(const item of central){const c=new Uint8Array([...u32(0x02014b50),...u16(20),...u16(20),...u16(0),...u16(0),...u16(dt.time),...u16(dt.day),...u32(item.crc),...u32(item.size),...u32(item.size),...u16(item.name.length),...u16(0),...u16(0),...u16(0),...u16(0),...u32(0),...u32(item.offset),...item.name]);parts.push(c);offset+=c.length;}const end=new Uint8Array([...u32(0x06054b50),...u16(0),...u16(0),...u16(central.length),...u16(central.length),...u32(offset-start),...u32(start),...u16(0)]);return new Blob([...chunks,...parts,end],{type:'application/zip'});}
  async function downloadAll(){if(!state.outputs.length)return notify('กรุณาสร้างภาพก่อนดาวน์โหลด');if(state.coverMode==='single'){downloadCover();return;}const order='วิธีใช้ชุด Facebook\n1. อัปโหลดภาพตามลำดับชื่อ 01, 02, 03... ห้ามสลับลำดับ\n2. ภาพ 01–02 เป็นปกที่ต่อกัน ภาพ 03–05 เป็นภาพกิจกรรมด้านล่าง\n3. หากมีมากกว่า 5 ภาพ Facebook จะแสดง +จำนวนบนภาพที่ 5\n4. ตรวจตัวอย่างอีกครั้งก่อนเผยแพร่ เพราะหน้าตากริดอาจต่างเล็กน้อยตามอุปกรณ์\n',extras=[{filename:'caption.txt',blob:new Blob([$('#albumCaptionText')?.value||state.caption],{type:'text/plain;charset=utf-8'})},{filename:'upload-order.txt',blob:new Blob([order],{type:'text/plain;charset=utf-8'})}],zip=await makeZip([...state.outputs,...extras]),link=document.createElement('a');link.href=URL.createObjectURL(zip);link.download=`tanjai-facebook-5-photo-pack-${Date.now()}.zip`;link.click();setTimeout(()=>URL.revokeObjectURL(link.href),1200);}
  function downloadCover(){const item=state.fullCover||state.outputs.find(output=>output.role==='cover');if(!item)return notify('กรุณาสร้างภาพปกก่อนดาวน์โหลด');const link=document.createElement('a');link.href=item.url;link.download='facebook-cover-full-2160x1080.jpg';link.click();}
  function downloadOne(index){const item=state.outputs[index];if(!item)return;const link=document.createElement('a');link.href=item.url;link.download=item.filename;link.click();}
  function copyCaption(button){const text=$('#albumCaptionText')?.value||state.caption;if(!text)return;navigator.clipboard?.writeText(text);const old=button.textContent;button.textContent='คัดลอกแล้ว ✓';setTimeout(()=>button.textContent=old,1300);}
  function saveProject(){const d=formData(),cover=selectedCover(),snapshot={...d,coverMode:state.coverMode,headlineX:state.headlineX,headlineY:state.headlineY,logoX:state.logoX,logoY:state.logoY,brandY:state.brandY,coverX:cover?.coverX||0,coverY:cover?.coverY||0,coverZoom:cover?.coverZoom||1,coverFit:cover?.coverFit||'fill'},payload=`【ข้อมูลงาน】\nหัวข้อ: ${d.title}\nหน่วยงาน: ${d.org}\nวันที่: ${d.date} ${d.time}\nสถานที่: ${d.place}\nรายละเอียด: ${d.detail}\n\n【แคปชั่น】\n${$('#albumCaptionText')?.value||state.caption}\n\n##TANJAI_ALBUM_V128##${JSON.stringify(snapshot)}`;window.TANJAI?.saveProject?.(d.title||'ชุดภาพโพสต์ Facebook',payload,'ชุดภาพโพสต์ Facebook');}
  function saveBrandProfile(){try{const d=formData();localStorage.setItem(BRAND_STORAGE_KEY,JSON.stringify({enabled:d.brandEnabled,slogan:d.brandSlogan,website:d.brandWebsite,social:d.brandSocial,phone:d.brandPhone}));notify('บันทึกข้อมูลแบรนด์ไว้ใช้ครั้งต่อไปแล้ว');}catch(_){notify('เบราว์เซอร์ไม่อนุญาตให้บันทึกข้อมูลแบรนด์');}}
  function loadBrandProfile(){try{const saved=JSON.parse(localStorage.getItem(BRAND_STORAGE_KEY)||'null');if(!saved)return;const map={slogan:'album-brandSlogan',website:'album-brandWebsite',social:'album-brandSocial',phone:'album-brandPhone'};Object.entries(map).forEach(([key,id])=>{const el=document.getElementById(id);if(el&&!el.value&&saved[key])el.value=saved[key];});const enabled=$('#album-brandEnabled');if(enabled&&typeof saved.enabled==='boolean')enabled.checked=saved.enabled;}catch(_){} }
  function clearAll(){revokeFiles();revokeOutputs();if(state.logoUrl)URL.revokeObjectURL(state.logoUrl);state.files=[];state.coverId=null;state.logo=null;state.logoUrl='';state.caption='';state.captionSource='';state.facts={};state.headlineX=50;state.headlineY=57;state.logoX=4;state.logoY=5;state.brandY=66;['album-allFiles','album-logoFile'].forEach(id=>{const el=document.getElementById(id);if(el)el.value='';});renderPhotoPicker();renderCoverEditor();renderCropList();renderEmptyResult();progress(false);}
  function setCoverMode(mode){state.coverMode=mode==='single'?'single':'double';const input=$('#album-coverMode');if(input)input.value=state.coverMode;$$('[data-cover-mode]').forEach(button=>button.classList.toggle('selected',button.dataset.coverMode===state.coverMode));renderCoverEditor();scheduleGeneratedRefresh();}
  function setPhotoFit(fit){const cover=selectedCover();if(!cover)return;cover.coverFit=fit==='contain'?'contain':'fill';if(cover.coverFit==='contain'&&cover.coverZoom<.5)cover.coverZoom=.5;renderCoverEditor();scheduleGeneratedRefresh();}
  function updateCoverPosition(input){const cover=selectedCover();if(!cover)return;const value=Number(input.value);if(input.id==='album-coverX')cover.coverX=value;if(input.id==='album-coverY')cover.coverY=value;if(input.id==='album-coverZoom')cover.coverZoom=Math.max(.5,Math.min(2.5,value/100));const photo=$('#albumPhotoDrag');if(photo){photo.style.left=(50+cover.coverX)+'%';photo.style.top=(50+cover.coverY)+'%';photo.style.transform=`translate(-50%,-50%) scale(${cover.coverZoom})`;}syncCoverControls(cover);scheduleGeneratedRefresh();}
  function useCoverTool(tool){
    if(tool==='headline'){const field=$('#album-title');field?.scrollIntoView?.({behavior:'smooth',block:'center'});setTimeout(()=>field?.focus(),250);return;}
    if(tool==='design'){const panel=$('#albumAdvancedEditor');if(panel){panel.open=true;panel.scrollIntoView?.({behavior:'smooth',block:'nearest'});}return;}
    if(tool==='reset'){const cover=selectedCover();if(cover){cover.coverX=0;cover.coverY=0;cover.coverZoom=1;cover.coverFit='fill';}state.headlineX=50;state.headlineY=57;state.logoX=formData().logoPosition==='right'?86:4;state.logoY=5;state.brandY=66;renderCoverEditor();scheduleGeneratedRefresh();notify('จัดตำแหน่งภาพและองค์ประกอบกลับค่าเริ่มต้นแล้ว');}
  }
  async function regenerateCaption(button){
    if(!state.outputs.length)return notify('กรุณาสร้างชุดภาพก่อน');
    state.caption=await generateSmartCaption(formData(),button);const area=$('#albumCaptionText');if(area)area.value=state.caption;renderFacebookPreview();notify('AI เรียบเรียงแคปชั่นใหม่แล้ว กรุณาตรวจข้อมูลก่อนโพสต์');
  }

  document.addEventListener('DOMContentLoaded',()=>{
    loadBrandProfile();renderCropList();renderEmptyResult();
    document.addEventListener('change',event=>{if(event.target.id==='album-allFiles')ingestFiles(event.target.files);if(event.target.id==='album-logoFile')loadLogo(event.target.files?.[0]||null);if(event.target.matches('[data-crop-axis]'))updateCrop(event.target);if(event.target.id==='album-logoPosition'){if(event.target.value==='right')state.logoX=86;if(event.target.value==='left')state.logoX=4;}if(['album-coverStyle','album-headlineFont','album-headlineWeight','album-headlineAlign','album-logoPosition','album-captionStyle','album-brandEnabled','album-bandStyle'].includes(event.target.id)){renderCoverEditor();scheduleGeneratedRefresh();}});
    document.addEventListener('input',event=>{if(event.target.matches('[data-crop-axis]'))updateCrop(event.target);if(['album-coverX','album-coverY','album-coverZoom'].includes(event.target.id)){updateCoverPosition(event.target);return;}if(event.target.id==='album-headlineSize')$('#album-fontSizeValue').textContent=event.target.value;if(event.target.id==='album-outlineWidth')$('#album-outlineValue').textContent=event.target.value;if(event.target.id==='album-logoSize')$('#album-logoSizeValue').textContent=event.target.value+'%';if(/^album-(title|orgName|headline|outline|logoSize|brand|band)/.test(event.target.id)||['album-headlineShadow','album-headlineItalic'].includes(event.target.id)){renderCoverEditor();scheduleGeneratedRefresh();}if(event.target.id==='albumCaptionText')renderFacebookPreview();});
    document.addEventListener('click',event=>{const tool=event.target.closest?.('[data-album-tool]');if(tool){event.preventDefault();useCoverTool(tool.dataset.albumTool);return;}const fit=event.target.closest?.('[data-photo-fit]');if(fit){event.preventDefault();setPhotoFit(fit.dataset.photoFit);return;}const mode=event.target.closest?.('[data-cover-mode]');if(mode){event.preventDefault();setCoverMode(mode.dataset.coverMode);return;}const cover=event.target.closest?.('[data-cover-id]');if(cover){event.preventDefault();state.coverId=cover.dataset.coverId;state.outputs.filter(item=>item.role==='photo').forEach(item=>URL.revokeObjectURL(item.url));state.outputs=state.outputs.filter(item=>item.role!=='photo');renderPhotoPicker();renderCoverEditor();renderCropList();scheduleGeneratedRefresh();return;}const move=event.target.closest?.('[data-move]');if(move){event.preventDefault();const card=move.closest('[data-file-id]');moveSupport(card?.dataset.fileId,move.dataset.move);return;}const id=event.target.id;if(id==='makeAlbum'){event.preventDefault();generate();}if(id==='albumDownloadAll'||id==='albumDownloadAllResult'){event.preventDefault();downloadAll();}if(id==='albumDownloadCover'||id==='albumDownloadCoverResult'){event.preventDefault();downloadCover();}if(id==='albumClear'){event.preventDefault();clearAll();}if(id==='albumCopyCaption'||id==='albumCopyCaptionQuick'){event.preventDefault();copyCaption(event.target);}if(id==='albumRegenerateCaptionAI'){event.preventDefault();regenerateCaption(event.target);}if(id==='albumRefreshPreview'){event.preventDefault();renderFacebookPreview();}if(id==='albumSaveProject'){event.preventDefault();saveProject();}if(id==='albumSaveBrandProfile'){event.preventDefault();saveBrandProfile();}const one=event.target.closest?.('.album-one-download');if(one){event.preventDefault();downloadOne(Number(one.dataset.index));}});
  });
  window.TANJAI=window.TANJAI||{};
  window.TANJAI.applyAlbumTemplate=function(snapshot){Object.entries(snapshot||{}).forEach(([key,value])=>{const id=key.startsWith('album-')?key:`album-${key}`,el=document.getElementById(id);if(!el||typeof value==='object')return;if(el.type==='checkbox')el.checked=!!value;else el.value=value;});if(snapshot?.coverMode)setCoverMode(snapshot.coverMode);if(Number.isFinite(snapshot?.headlineX))state.headlineX=snapshot.headlineX;if(Number.isFinite(snapshot?.headlineY))state.headlineY=snapshot.headlineY;if(Number.isFinite(snapshot?.logoX))state.logoX=snapshot.logoX;if(Number.isFinite(snapshot?.logoY))state.logoY=snapshot.logoY;if(Number.isFinite(snapshot?.brandY))state.brandY=snapshot.brandY;const cover=selectedCover();if(cover){if(Number.isFinite(snapshot?.coverX))cover.coverX=snapshot.coverX;if(Number.isFinite(snapshot?.coverY))cover.coverY=snapshot.coverY;if(Number.isFinite(snapshot?.coverZoom))cover.coverZoom=snapshot.coverZoom;if(snapshot?.coverFit)cover.coverFit=snapshot.coverFit;}renderCoverEditor();};
  window.TANJAI_ALBUM_PRO={generate,downloadAll,downloadCover,renderFacebookPreview,renderPhotoPicker,renderCropList,_test:{cropPlacement,coverPlacement,captionWriter,factGuardCaption,short,metaText,headlineFontSize,normalizeFacts,cleanMultiline,wrapHeadlineLines,brandContacts,hasBrandContent}};
})();
