window.TANJAI = window.TANJAI || {};

(() => {
  const state = {
    clips: [], timeline: [], activeClipId: null, mode: 'editor',
    analysis: null, storyOptions: [], selectedStory: 0, voiceScript: ''
  };
  const $ = (s, root=document) => root.querySelector(s);
  const $$ = (s, root=document) => Array.from(root.querySelectorAll(s));
  const uid = () => `clip-${Date.now()}-${Math.random().toString(36).slice(2,8)}`;
  const esc = v => TANJAI.escapeHTML ? TANJAI.escapeHTML(v) : String(v||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const fmtTime = (sec=0) => { const s=Math.max(0,Math.round(Number(sec)||0)); return `${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`; };
  const fmtSize = bytes => { const n=Number(bytes)||0; return n<1048576?`${Math.round(n/1024)} KB`:`${(n/1048576).toFixed(1)} MB`; };
  const clipById = id => state.clips.find(c=>c.id===id);

  function install(){
    const form=$('#videoForm'), result=$('#videoResult');
    if(!form||!result||$('#videoEditorWorkspace')) return;
    const original=document.createElement('div'); original.id='videoScriptMode'; while(form.firstChild) original.appendChild(form.firstChild);
    form.appendChild(document.createRange().createContextualFragment(`<div class="video-mode-switch" role="tablist"><button type="button" class="video-mode-btn" data-video-mode="script">📝 คิดบทก่อนถ่าย</button><button type="button" class="video-mode-btn active" data-video-mode="editor">🎬 วิเคราะห์ฟุตเทจ</button></div>`));
    form.appendChild(original);
    const editor=document.createElement('div'); editor.id='videoEditorWorkspace'; editor.innerHTML=editorHTML(); form.appendChild(editor);
    const originalResult=document.createElement('div'); originalResult.id='videoScriptResultMode'; while(result.firstChild) originalResult.appendChild(result.firstChild); result.appendChild(originalResult);
    const editorResult=document.createElement('div'); editorResult.id='videoEditorResultMode'; editorResult.innerHTML=resultHTML(); result.appendChild(editorResult);
    bind(); setMode('editor'); renderAll();
  }

  function editorHTML(){return `
    <div class="form-note video-editor-note"><b>โยนฟุตเทจมา แล้วให้ AI ช่วยดูให้</b><span>ระบบจะตรวจคุณภาพ แยกกลุ่ม เลือกช็อต และเสนอแนวเล่าเรื่องพร้อมบทพากย์</span></div>
    <div class="form-section">
      <div class="section-title"><b>1</b><h4>เพิ่มฟุตเทจ</h4></div>
      <label class="video-dropzone" id="videoDropzone"><input id="videoFootageInput" type="file" accept="video/*" multiple hidden><span class="video-drop-icon">🎞️</span><strong>ลากคลิปมาวาง หรือกดเลือกหลายคลิป</strong><small>เลือกได้ครั้งละหลายไฟล์ ระบบอ่านคลิปจากเครื่องโดยตรง</small><button class="btn primary" type="button" id="pickFootageBtn">เลือกฟุตเทจ</button></label>
      <div class="video-upload-summary" id="videoUploadSummary">ยังไม่มีฟุตเทจ</div><div class="video-clip-grid" id="videoClipGrid"></div>
    </div>
    <div class="form-section">
      <div class="section-title"><b>2</b><h4>บอกบริบทของงาน</h4></div>
      <div class="form-grid">
        <label>ประเภทงาน<select id="editPurpose"><option>ข่าวประชาสัมพันธ์เทศบาล</option><option>ไฮไลต์กิจกรรม</option><option>ผู้บริหารลงพื้นที่</option><option>โครงการ / อบรม</option><option>ประชุม / ประชาคม</option><option>สัมภาษณ์</option><option>รีวิว / แนะนำสถานที่</option><option>MV / เพลง</option><option>คลิปสั้น Reel / TikTok / Shorts</option><option>อื่น ๆ</option></select></label>
        <label>อารมณ์ของคลิป<select id="editTone"><option>ทางการ กระชับ น่าเชื่อถือ</option><option>อบอุ่น เป็นกันเอง</option><option>สดใส สนุก มีพลัง</option><option>ซาบซึ้ง สร้างแรงบันดาลใจ</option><option>ทันสมัย เร็ว ดึงดูด</option></select></label>
        <label>ความยาวเป้าหมาย<select id="editTargetLength"><option value="30">30 วินาที</option><option value="60">1 นาที</option><option value="180" selected>3 นาที</option><option value="300">5 นาที</option><option value="0">ให้ AI เลือก</option></select></label>
        <label>สัดส่วน<select id="editAspect"><option value="16:9">แนวนอน 16:9</option><option value="9:16">แนวตั้ง 9:16</option><option value="4:5">แนวตั้ง 4:5</option><option value="1:1">จัตุรัส 1:1</option><option value="source">ตามต้นฉบับ</option></select></label>
        <label class="full">ชื่องาน / รายละเอียดที่ต้องกล่าวถึง<textarea id="editContext" placeholder="เช่น โครงการร่วมกิจกรรมร่วมใจเพื่อผู้สูงวัยบางรักน้อย วันที่... ณ..."></textarea></label>
        <label class="full">เน้นอะไรเป็นพิเศษ <span class="optional-label">ไม่บังคับ</span><textarea id="editInstruction" placeholder="เช่น เน้นประชาชนร่วมกิจกรรม เปิดด้วยภาพรอยยิ้ม จบด้วยภาพหมู่"></textarea></label>
        <label class="video-auto-enhance full"><input id="autoEnhance" type="checkbox" checked><span><b>ให้ AI ปรับคุณภาพคลิปอัตโนมัติ</b><small>วิเคราะห์แสง สี ความคม เสียง และความเหมาะสมของแต่ละคลิป</small></span></label>
      </div>
      <div class="button-row"><button class="btn primary video-create-kit-btn" id="analyzeFootageBtn" type="button">✨ วิเคราะห์ฟุตเทจให้เลย</button><button class="btn secondary" id="clearFootageBtn" type="button">ล้างฟุตเทจ</button></div>
      <div class="ai-work-progress" id="aiWorkProgress" hidden><b>AI กำลังช่วยดูฟุตเทจ</b><div class="ai-progress-bar"><i id="aiProgressFill"></i></div><div id="aiProgressText">กำลังเตรียมงาน...</div></div>
    </div>`;}

  function resultHTML(){return `
    <div class="editor-result-head"><div><small>ทันใจ AI FOOTAGE ASSISTANT</small><h3>ผลวิเคราะห์ฟุตเทจ</h3><p id="editorResultStatus">เพิ่มฟุตเทจและบอกบริบทของงาน</p></div><span class="editor-status-pill" id="editorStatusPill">รอไฟล์</span></div>
    <div class="editor-stats" id="editorStats"></div>
    <section class="footage-insight-panel" id="footageInsightPanel"><div class="editor-empty-preview"><span>🧠</span><b>AI จะสรุปสิ่งที่พบตรงนี้</b><small>คลิปดี คลิปควรตรวจ กลุ่มเหตุการณ์ และคำแนะนำ</small></div></section>
    <section id="storyOptionsSection" hidden><div class="timeline-toolbar"><div><b>แนวเล่าเรื่องที่แนะนำ</b><small>เลือกแนวที่ตรงกับงาน แล้วแก้ได้ภายหลัง</small></div></div><div class="story-option-grid" id="storyOptionGrid"></div></section>
    <section id="voiceScriptSection" hidden class="voice-script-panel"><div class="timeline-toolbar"><div><b>สคริปต์เสียงพากย์</b><small>สร้างจากบริบทและคลิปที่ AI เลือก</small></div><button class="btn secondary" id="copyVoiceScriptBtn" type="button">คัดลอก</button></div><textarea id="voiceScriptText"></textarea></section>
    <section id="selectedClipsSection" hidden><div class="timeline-toolbar"><div><b>คลิปที่ AI เลือกให้</b><small>เรียงตามลำดับเรื่อง พร้อมเหตุผลที่เลือก</small></div><button class="btn secondary" id="autoArrangeBtn" type="button">จัดใหม่</button></div><div class="smart-timeline" id="smartTimeline"></div></section>
    <div class="editor-preview-stage" id="editorPreviewStage"><div class="editor-empty-preview"><span>🎬</span><b>ตัวอย่างคลิปจะอยู่ตรงนี้</b><small>หลังวิเคราะห์ กดคลิปที่เลือกเพื่อดูตัวอย่าง</small></div></div>
    <div class="editor-export-box" id="editorExportBox" hidden><div><b>เลือกว่าจะทำต่อแบบไหน</b><small>ตัดเอง: ดาวน์โหลดคลิปจริงที่ AI เลือกกลับไปใช้ได้ทันที • ให้ AI ตัด: บันทึกแผนงานไว้ต่อระบบอัตโนมัติ</small></div><div class="button-row"><button class="btn primary" id="downloadSelectedClipsBtn" type="button">⬇ ดาวน์โหลดคลิปที่ AI เลือก (.ZIP)</button><button class="btn secondary" id="downloadClipListBtn" type="button">รายชื่อคลิป</button><button class="btn secondary" id="downloadEditPlanBtn" type="button">บันทึกแผนตัดต่อ</button><button class="btn secondary" id="prepareAutoEditBtn" type="button">เตรียมให้ AI ตัดต่อ</button></div><small class="export-help">ไฟล์ ZIP จะมีคลิปต้นฉบับที่เลือก เรียงเลขตามลำดับเรื่อง พร้อมสคริปต์และรายการตัดต่อ</small></div>`;}

  function bind(){
    $$('[data-video-mode]').forEach(b=>b.addEventListener('click',()=>setMode(b.dataset.videoMode)));
    $('#pickFootageBtn')?.addEventListener('click',()=>$('#videoFootageInput')?.click());
    $('#videoFootageInput')?.addEventListener('change',e=>addFiles(e.target.files));
    const dz=$('#videoDropzone'); ['dragenter','dragover'].forEach(t=>dz?.addEventListener(t,e=>{e.preventDefault();dz.classList.add('dragging')})); ['dragleave','drop'].forEach(t=>dz?.addEventListener(t,e=>{e.preventDefault();dz.classList.remove('dragging')})); dz?.addEventListener('drop',e=>addFiles(e.dataTransfer.files));
    $('#clearFootageBtn')?.addEventListener('click',clearFiles); $('#analyzeFootageBtn')?.addEventListener('click',analyzeAll); $('#autoArrangeBtn')?.addEventListener('click',()=>autoArrange(true));
    $('#copyVoiceScriptBtn')?.addEventListener('click',async()=>{const text=$('#voiceScriptText')?.value||''; try{await navigator.clipboard.writeText(text);TANJAI.toast('คัดลอกสคริปต์แล้ว')}catch(_){TANJAI.toast('เลือกข้อความแล้วกดคัดลอกได้เลย')}});
    $('#downloadEditPlanBtn')?.addEventListener('click',downloadPlan); $('#downloadClipListBtn')?.addEventListener('click',downloadClipList); $('#downloadSelectedClipsBtn')?.addEventListener('click',downloadSelectedClipsZip);
    $('#prepareAutoEditBtn')?.addEventListener('click',()=>TANJAI.toast('บันทึกชุดงานพร้อมส่งต่อระบบตัดอัตโนมัติแล้ว'));
  }
  function setMode(mode){state.mode=mode; $('#videoScriptMode').hidden=mode!=='script'; $('#videoEditorWorkspace').hidden=mode!=='editor'; $('#videoScriptResultMode').hidden=mode!=='script'; $('#videoEditorResultMode').hidden=mode!=='editor'; $$('[data-video-mode]').forEach(b=>b.classList.toggle('active',b.dataset.videoMode===mode));}

  async function addFiles(fileList){
    const files=Array.from(fileList||[]).filter(f=>f.type.startsWith('video/')); if(!files.length){TANJAI.toast('กรุณาเลือกไฟล์วิดีโอ');return;}
    const remaining=Math.max(0,100-state.clips.length);
    files.slice(0,remaining).forEach(file=>{const clip={id:uid(),file,name:file.name,size:file.size,url:URL.createObjectURL(file),duration:0,width:0,height:0,orientation:'กำลังอ่าน',thumbnail:'',brightness:null,sharpness:null,audioLevel:null,flags:[],score:50,status:'loading',category:'กำลังวิเคราะห์',reason:'รอวิเคราะห์'};state.clips.push(clip);inspectMetadata(clip)});
    state.analysis=null; renderAll(); TANJAI.toast(`เพิ่มฟุตเทจ ${Math.min(files.length,remaining)} คลิปแล้ว`);
  }
  function inspectMetadata(clip){const v=document.createElement('video');v.preload='metadata';v.muted=true;v.src=clip.url;v.onloadedmetadata=()=>{clip.duration=Number(v.duration)||0;clip.width=v.videoWidth||0;clip.height=v.videoHeight||0;clip.orientation=clip.width===clip.height?'จัตุรัส':clip.width>clip.height?'แนวนอน':'แนวตั้ง';clip.status='ready';if(clip.duration<2)clip.flags.push('สั้นเกินไป');captureFrame(clip,Math.min(Math.max(clip.duration*.28,.1),Math.max(.1,clip.duration-.1)));renderAll()};v.onerror=()=>{clip.status='error';clip.flags.push('เปิดไฟล์ไม่ได้');updateScore(clip);renderAll()};}
  function captureFrame(clip,time){const v=document.createElement('video');v.muted=true;v.playsInline=true;v.src=clip.url;v.onloadedmetadata=()=>{try{v.currentTime=time}catch(_){}};v.onseeked=()=>{try{const w=320,h=Math.max(180,Math.round(w*(v.videoHeight/v.videoWidth||.5625))),c=document.createElement('canvas'),ctx=c.getContext('2d',{willReadFrequently:true});c.width=w;c.height=h;ctx.drawImage(v,0,0,w,h);clip.thumbnail=c.toDataURL('image/jpeg',.72);const m=imageMetrics(ctx.getImageData(0,0,w,h),w,h);clip.brightness=m.brightness;clip.sharpness=m.sharpness;if(m.brightness<45)clip.flags.push('แสงน้อย');else if(m.brightness>210)clip.flags.push('สว่างเกิน');if(m.sharpness<9)clip.flags.push('อาจไม่คม');updateScore(clip)}catch(e){console.warn(e)}renderAll()};}
  function imageMetrics(img,w,h){const d=img.data,g=new Float32Array(w*h);let lum=0,edge=0,n=0;for(let i=0,p=0;i<d.length;i+=4,p++){g[p]=.299*d[i]+.587*d[i+1]+.114*d[i+2];lum+=g[p]}for(let y=1;y<h-1;y+=2)for(let x=1;x<w-1;x+=2){const p=y*w+x;edge+=Math.abs(g[p-1]-g[p+1])+Math.abs(g[p-w]-g[p+w]);n++}return{brightness:lum/(w*h),sharpness:n?edge/n:0};}
  function updateScore(c){let s=82;if(c.duration<2)s-=38;else if(c.duration<4)s-=10;if(c.flags.includes('แสงน้อย'))s-=17;if(c.flags.includes('สว่างเกิน'))s-=12;if(c.flags.includes('อาจไม่คม'))s-=18;if(c.flags.includes('เสียงเบามาก / เงียบ'))s-=10;if(c.status==='error')s=0;c.score=Math.max(0,Math.min(100,Math.round(s)));}
  async function analyzeAudio(c){if(c.status==='error')return;try{const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return;const ac=new AC(),buf=await c.file.arrayBuffer(),decoded=await ac.decodeAudioData(buf.slice(0));let sum=0,n=0;for(let ch=0;ch<decoded.numberOfChannels;ch++){const data=decoded.getChannelData(ch),step=Math.max(1,Math.floor(data.length/16000));for(let i=0;i<data.length;i+=step){sum+=data[i]*data[i];n++}}c.audioLevel=n?Math.sqrt(sum/n):0;if(c.audioLevel<.006)c.flags.push('เสียงเบามาก / เงียบ');await ac.close()}catch(_){c.audioLevel=null}updateScore(c);}

  async function analyzeAll(){
    if(!state.clips.length){TANJAI.toast('กรุณาเพิ่มฟุตเทจก่อน');return;}
    const btn=$('#analyzeFootageBtn');btn.disabled=true; const steps=['กำลังอ่านข้อมูลคลิปทั้งหมด','กำลังตรวจแสง สี ความคม และเสียง','กำลังแยกกลุ่มเหตุการณ์','กำลังเลือกช็อตที่เหมาะกับเรื่อง','กำลังสร้างแนวเล่าเรื่องและบทพากย์'];
    $('#aiWorkProgress').hidden=false; $('#editorStatusPill').textContent='AI กำลังทำงาน';
    for(let i=0;i<steps.length;i++){setProgress(i+1,steps.length,steps[i]);if(i===1)await Promise.all(state.clips.map(analyzeAudio));else await wait(320)}
    categorizeClips(); autoArrange(false); buildAnalysis(); buildStoryOptions(); selectStory(0); setProgress(steps.length,steps.length,'เสร็จแล้ว');
    btn.disabled=false;btn.textContent='✨ วิเคราะห์ใหม่อีกครั้ง';$('#editorStatusPill').textContent='พร้อมใช้งาน';$('#editorResultStatus').textContent='AI แยกคลิป เลือกช็อต และเตรียมแนวเล่าเรื่องแล้ว'; renderAll(); TANJAI.toast('วิเคราะห์ฟุตเทจเรียบร้อยแล้ว'); setTimeout(()=>{$('#aiWorkProgress').hidden=true},900);
  }
  const wait=ms=>new Promise(r=>setTimeout(r,ms)); function setProgress(now,total,text){$('#aiProgressFill').style.width=`${now/total*100}%`;$('#aiProgressText').textContent=`${text} (${now}/${total})`;}
  function categorizeClips(){
    const purpose=$('#editPurpose').value;
    state.clips.forEach((c,i)=>{const name=c.name.toLowerCase();let cat='ภาพบรรยากาศ';if(/open|intro|sign|logo|banner|ป้าย|เปิด/.test(name)||i===0)cat='ภาพเปิดเรื่อง';else if(/speech|talk|interview|สัมภาษณ์|กล่าว|ประธาน|นายก/.test(name)||(c.audioLevel||0)>.025)cat='ช่วงพูด / สัมภาษณ์';else if(/group|photo|รวม|หมู่|award|มอบ/.test(name)||i===state.clips.length-1)cat='ภาพสรุป / ปิดเรื่อง';else if(c.duration<6)cat='ช็อตเสริม';else if(purpose.includes('ประชุม'))cat='การประชุม';else if(purpose.includes('MV'))cat='ภาพตามจังหวะเพลง';else if(i%4===1)cat='กิจกรรมหลัก';else if(i%4===2)cat='ประชาชน / ผู้ร่วมงาน';c.category=cat;c.reason=c.score>=75?`ภาพคุณภาพดี เหมาะใช้ในช่วง${cat}`:c.score>=55?`ใช้ได้ แนะนำตรวจช่วงต้นและท้าย`:c.flags.join(', ')||'ควรตรวจเพิ่มเติม';});
  }
  function buildAnalysis(){const groups={};state.clips.forEach(c=>groups[c.category]=(groups[c.category]||0)+1);state.analysis={total:state.clips.length,usable:state.clips.filter(c=>c.score>=60).length,review:state.clips.filter(c=>c.score<60).length,totalDuration:state.clips.reduce((s,c)=>s+c.duration,0),groups};}
  function buildStoryOptions(){const purpose=$('#editPurpose').value,tone=$('#editTone').value,target=Number($('#editTargetLength').value||180);const d=target||Math.min(180,Math.max(45,state.analysis.totalDuration*.35));state.storyOptions=[
    {title:'เล่าเรื่องครบ กระชับ',badge:'แนะนำ',duration:d,structure:['ภาพเปิดที่ดึงความสนใจ','แนะนำงานและวัตถุประสงค์','กิจกรรมสำคัญและผู้เข้าร่วม','ช่วงเด่น / คำกล่าว','สรุปผลและภาพปิด'],focus:'ครบข้อมูล ใช้งานประชาสัมพันธ์ได้ทันที'},
    {title:'เน้นบรรยากาศและความรู้สึก',badge:'อบอุ่น',duration:Math.min(d,90),structure:['รอยยิ้มหรือช็อตเด่น','ภาพกิจกรรมต่อเนื่อง','ประชาชนมีส่วนร่วม','คำพูดสั้นที่มีความหมาย','ภาพรวมและความประทับใจ'],focus:`เหมาะกับโทน ${tone}`},
    {title:'ไฮไลต์เร็วสำหรับโซเชียล',badge:'คลิปสั้น',duration:Math.min(45,d),structure:['ช็อตเด่นใน 3 วินาทีแรก','กิจกรรมสลับเร็ว','ข้อความสำคัญบนจอ','ภาพคนและปฏิกิริยา','จบด้วยชื่อหน่วยงาน / ช่องทาง'],focus:'เหมาะกับ Reel, TikTok และ Shorts'}
  ];}
  function selectStory(index){state.selectedStory=index;const story=state.storyOptions[index];if(!story)return;state.voiceScript=generateVoiceScript(story);autoArrange(false,story.duration);renderAll();}
  function generateVoiceScript(story){const context=($('#editContext').value||'กิจกรรมครั้งนี้').trim(),purpose=$('#editPurpose').value,tone=$('#editTone').value,groups=state.analysis?.groups||{};const groupText=Object.entries(groups).slice(0,4).map(([k,v])=>`${k} ${v} คลิป`).join(', ');return `เปิดเรื่อง\n${context}\n\nบทพากย์\n${purpose} จัดขึ้นเพื่อสื่อสารเรื่องราวและบรรยากาศสำคัญให้ประชาชนได้รับทราบอย่างทั่วถึง ภายในงานมีทั้งกิจกรรมหลัก การมีส่วนร่วมของผู้เข้าร่วม และช่วงเวลาที่สะท้อนถึงความตั้งใจของผู้จัดงาน\n\nจากฟุตเทจที่ตรวจพบ ระบบได้คัดเลือก ${groupText || 'ภาพเหตุการณ์สำคัญ'} เพื่อนำมาเรียบเรียงให้เรื่องราวต่อเนื่อง เข้าใจง่าย และมีอารมณ์แบบ${tone}\n\nตลอดกิจกรรม ผู้เข้าร่วมได้ร่วมกันสร้างบรรยากาศที่มีคุณค่า พร้อมสะท้อนถึงความร่วมมือและผลลัพธ์ที่เกิดขึ้นจริง\n\nปิดเรื่อง\n${context} อีกหนึ่งกิจกรรมที่ช่วยเชื่อมโยงหน่วยงานกับประชาชน และสร้างประโยชน์ร่วมกันอย่างเป็นรูปธรรม`;} 

  function autoArrange(notify=true,forcedDuration){const target=forcedDuration??Number($('#editTargetLength').value||180),aspect=$('#editAspect').value;let list=state.clips.filter(c=>c.status!=='error'&&c.score>=45);const catOrder={'ภาพเปิดเรื่อง':0,'ช่วงพูด / สัมภาษณ์':2,'กิจกรรมหลัก':3,'ประชาชน / ผู้ร่วมงาน':4,'การประชุม':4,'ภาพตามจังหวะเพลง':4,'ภาพบรรยากาศ':5,'ช็อตเสริม':6,'ภาพสรุป / ปิดเรื่อง':9};list.sort((a,b)=>{const orient=c=>aspect==='source'?0:((aspect==='16:9'&&c.orientation==='แนวนอน')||(aspect!=='16:9'&&c.orientation==='แนวตั้ง')?8:0);return (catOrder[a.category]??5)-(catOrder[b.category]??5)||((b.score+orient(b))-(a.score+orient(a)))});const chosen=[];let total=0;for(const c of list){if(target&&total>=target)break;const use=Math.min(c.duration||0,state.selectedStory===2?4:8,target?Math.max(1,target-total):8);if(use>.5){chosen.push({clipId:c.id,start:0,end:use,duration:use,reason:c.reason});total+=use}}state.timeline=chosen;state.activeClipId=chosen[0]?.clipId||null;if(notify){renderAll();TANJAI.toast('จัดลำดับคลิปใหม่แล้ว')}}

  function renderAll(){renderClips();renderStats();renderInsights();renderStories();renderTimeline();renderPreview();}
  function renderClips(){const grid=$('#videoClipGrid');if(!grid)return;const totalSize=state.clips.reduce((s,c)=>s+c.size,0);$('#videoUploadSummary').textContent=state.clips.length?`${state.clips.length} คลิป • ${fmtSize(totalSize)} • ความยาวรวม ${fmtTime(state.clips.reduce((s,c)=>s+c.duration,0))}`:'ยังไม่มีฟุตเทจ';grid.innerHTML=state.clips.map(c=>`<article class="video-clip-card ${c.score<60?'warning':''}"><div class="clip-thumb">${c.thumbnail?`<img src="${c.thumbnail}" alt="">`:'<span>🎞️</span>'}<small>${fmtTime(c.duration)}</small></div><div class="clip-card-body"><b title="${esc(c.name)}">${esc(c.name)}</b><span>${c.orientation} • ${fmtSize(c.size)}</span><div class="clip-quality"><i style="width:${c.score}%"></i></div><small>${c.category} • คะแนน ${c.score}/100</small><div class="clip-flags">${c.flags.length?c.flags.map(f=>`<em>${esc(f)}</em>`).join(''):'<em class="ok">พร้อมใช้</em>'}</div></div><button class="clip-remove" type="button" data-remove-clip="${c.id}">×</button></article>`).join('');$$('[data-remove-clip]',grid).forEach(b=>b.onclick=()=>removeClip(b.dataset.removeClip));}
  function renderStats(){const a=state.analysis||{total:state.clips.length,usable:state.clips.filter(c=>c.score>=60).length,review:state.clips.filter(c=>c.score<60).length,totalDuration:state.clips.reduce((s,c)=>s+c.duration,0)};$('#editorStats').innerHTML=`<article><small>คลิปทั้งหมด</small><b>${a.total}</b></article><article><small>AI เลือกให้</small><b>${state.timeline.length}</b></article><article><small>ควรตรวจ</small><b>${a.review}</b></article><article><small>ความยาวรวม</small><b>${fmtTime(a.totalDuration)}</b></article>`;if(!state.clips.length)$('#editorStatusPill').textContent='รอไฟล์';else if(!state.analysis)$('#editorStatusPill').textContent='พร้อมวิเคราะห์';}
  function renderInsights(){const panel=$('#footageInsightPanel');if(!state.analysis){panel.innerHTML='<div class="editor-empty-preview"><span>🧠</span><b>AI จะสรุปสิ่งที่พบตรงนี้</b><small>คลิปดี คลิปควรตรวจ กลุ่มเหตุการณ์ และคำแนะนำ</small></div>';return;}const groups=Object.entries(state.analysis.groups).sort((a,b)=>b[1]-a[1]);panel.innerHTML=`<div class="insight-summary"><h4>AI ดูคลิปทั้งหมดแล้ว</h4><p>พบคลิปพร้อมใช้ <b>${state.analysis.usable}</b> คลิป และคลิปที่ควรตรวจ <b>${state.analysis.review}</b> คลิป</p></div><div class="clip-group-grid">${groups.map(([g,n])=>`<article><b>${n}</b><span>${esc(g)}</span></article>`).join('')}</div><div class="director-note"><b>คำแนะนำของ AI</b><p>${state.analysis.usable>=6?'ฟุตเทจมีเพียงพอสำหรับทำเรื่องได้หลายรูปแบบ แนะนำใช้ช็อตคุณภาพสูงเปิดเรื่อง แล้วสลับภาพกิจกรรมกับช่วงพูดเพื่อไม่ให้คลิปนิ่งเกินไป':'ฟุตเทจที่พร้อมใช้ยังมีไม่มาก แนะนำทำคลิปสั้น หรือเพิ่มภาพบรรยากาศและภาพปิดเรื่อง'}</p></div>`;}
  function renderStories(){const sec=$('#storyOptionsSection'),voice=$('#voiceScriptSection'),selected=$('#selectedClipsSection'),exp=$('#editorExportBox');if(!state.analysis){sec.hidden=voice.hidden=selected.hidden=exp.hidden=true;return;}sec.hidden=voice.hidden=selected.hidden=exp.hidden=false;$('#storyOptionGrid').innerHTML=state.storyOptions.map((s,i)=>`<button type="button" class="story-option ${i===state.selectedStory?'active':''}" data-story="${i}"><small>${s.badge}</small><b>${s.title}</b><span>${fmtTime(s.duration)} • ${s.focus}</span><ol>${s.structure.map(x=>`<li>${esc(x)}</li>`).join('')}</ol></button>`).join('');$$('[data-story]').forEach(b=>b.onclick=()=>selectStory(Number(b.dataset.story)));$('#voiceScriptText').value=state.voiceScript;}
  function renderTimeline(){const el=$('#smartTimeline');if(!el)return;if(!state.timeline.length){el.innerHTML='<div class="timeline-empty">AI ยังไม่ได้เลือกคลิป</div>';return;}el.innerHTML=state.timeline.map((t,i)=>{const c=clipById(t.clipId);return c?`<article class="timeline-item ${state.activeClipId===c.id?'active':''}" data-select-timeline="${c.id}"><div class="timeline-index">${i+1}</div><div class="timeline-thumb">${c.thumbnail?`<img src="${c.thumbnail}" alt="">`:'🎞️'}</div><div class="timeline-info"><b>${esc(c.name)}</b><span>${c.category} • ${fmtTime(t.start)}–${fmtTime(t.end)}</span><small>${esc(c.reason)}</small></div><div class="timeline-actions"><button type="button" data-move="-1" data-index="${i}">↑</button><button type="button" data-move="1" data-index="${i}">↓</button><button type="button" data-remove-timeline="${i}">×</button></div></article>`:''}).join('');$$('[data-select-timeline]',el).forEach(x=>x.onclick=e=>{if(e.target.closest('button'))return;state.activeClipId=x.dataset.selectTimeline;renderPreview();$$('.timeline-item').forEach(y=>y.classList.toggle('active',y===x))});$$('[data-move]',el).forEach(b=>b.onclick=()=>moveTimeline(Number(b.dataset.index),Number(b.dataset.move)));$$('[data-remove-timeline]',el).forEach(b=>b.onclick=()=>removeTimeline(Number(b.dataset.removeTimeline)));}
  function renderPreview(){const stage=$('#editorPreviewStage'),c=clipById(state.activeClipId);if(!c){stage.innerHTML='<div class="editor-empty-preview"><span>🎬</span><b>ตัวอย่างคลิปจะอยู่ตรงนี้</b><small>หลังวิเคราะห์ กดคลิปที่เลือกเพื่อดูตัวอย่าง</small></div>';return;}const t=state.timeline.find(x=>x.clipId===c.id);stage.innerHTML=`<video src="${c.url}#t=${t?.start||0},${t?.end||c.duration}" controls playsinline preload="metadata"></video><div class="preview-caption"><b>${esc(c.name)}</b><span>${c.category} • คะแนน ${c.score}/100</span></div>`;}
  function moveTimeline(i,d){const n=i+d;if(n<0||n>=state.timeline.length)return;[state.timeline[i],state.timeline[n]]=[state.timeline[n],state.timeline[i]];renderTimeline()} function removeTimeline(i){state.timeline.splice(i,1);state.activeClipId=state.timeline[0]?.clipId||null;renderAll()}
  function removeClip(id){const c=clipById(id);if(c)URL.revokeObjectURL(c.url);state.clips=state.clips.filter(x=>x.id!==id);state.timeline=state.timeline.filter(x=>x.clipId!==id);state.analysis=null;renderAll()}
  function clearFiles(){state.clips.forEach(c=>URL.revokeObjectURL(c.url));state.clips=[];state.timeline=[];state.analysis=null;state.storyOptions=[];state.voiceScript='';state.activeClipId=null;const input=$('#videoFootageInput');if(input)input.value='';renderAll();TANJAI.toast('ล้างฟุตเทจแล้ว')}

  function sanitizeFileName(name='file'){return String(name).replace(/[\\/:*?"<>|]/g,'_').replace(/\s+/g,' ').trim()||'file'}
  function crc32(bytes){let c=0xffffffff;for(const b of bytes){c^=b;for(let k=0;k<8;k++)c=(c>>>1)^((c&1)?0xedb88320:0)}return (c^0xffffffff)>>>0}
  function u16(n){return new Uint8Array([n&255,(n>>>8)&255])}
  function u32(n){return new Uint8Array([n&255,(n>>>8)&255,(n>>>16)&255,(n>>>24)&255])}
  function joinBytes(parts){const len=parts.reduce((n,p)=>n+p.length,0),out=new Uint8Array(len);let o=0;for(const p of parts){out.set(p,o);o+=p.length}return out}
  function dosDateTime(d=new Date()){let year=Math.max(1980,d.getFullYear());return {time:(d.getHours()<<11)|(d.getMinutes()<<5)|(d.getSeconds()>>1),date:((year-1980)<<9)|((d.getMonth()+1)<<5)|d.getDate()}}
  async function makeStoreZip(entries){const enc=new TextEncoder(),locals=[],centrals=[];let offset=0;for(const e of entries){const name=enc.encode(e.name),data=e.data instanceof Uint8Array?e.data:new Uint8Array(await e.data.arrayBuffer()),crc=crc32(data),dt=dosDateTime(e.date||new Date());const local=joinBytes([u32(0x04034b50),u16(20),u16(0x0800),u16(0),u16(dt.time),u16(dt.date),u32(crc),u32(data.length),u32(data.length),u16(name.length),u16(0),name,data]);locals.push(local);const central=joinBytes([u32(0x02014b50),u16(20),u16(20),u16(0x0800),u16(0),u16(dt.time),u16(dt.date),u32(crc),u32(data.length),u32(data.length),u16(name.length),u16(0),u16(0),u16(0),u16(0),u32(0),u32(offset),name]);centrals.push(central);offset+=local.length}const centralSize=centrals.reduce((n,p)=>n+p.length,0),end=joinBytes([u32(0x06054b50),u16(0),u16(0),u16(entries.length),u16(entries.length),u32(centralSize),u32(offset),u16(0)]);return new Blob([...locals,...centrals,end],{type:'application/zip'})}
  async function downloadSelectedClipsZip(){if(!state.timeline.length){TANJAI.toast('ยังไม่มีคลิปที่ AI เลือก');return}const btn=$('#downloadSelectedClipsBtn'),old=btn?.textContent;if(btn){btn.disabled=true;btn.textContent='กำลังรวมคลิป...'}try{const entries=[],used=new Map();for(let i=0;i<state.timeline.length;i++){const t=state.timeline[i],c=clipById(t.clipId);if(!c?.file)continue;let base=sanitizeFileName(c.name),key=base.toLowerCase(),count=(used.get(key)||0)+1;used.set(key,count);if(count>1){const dot=base.lastIndexOf('.');base=dot>0?`${base.slice(0,dot)}-${count}${base.slice(dot)}`:`${base}-${count}`}entries.push({name:`คลิปที่เลือก/${String(i+1).padStart(2,'0')}-${base}`,data:c.file,date:new Date(c.file.lastModified||Date.now())})}const csv=['ลำดับ,ชื่อไฟล์,กลุ่ม,เริ่ม,จบ,คะแนน,เหตุผล',...state.timeline.map((t,i)=>{const c=clipById(t.clipId);return `${i+1},"${(c?.name||'').replace(/"/g,'""')}","${c?.category||''}",${t.start.toFixed(1)},${t.end.toFixed(1)},${c?.score||0},"${(c?.reason||'').replace(/"/g,'""')}"`})].join('\n');entries.push({name:'แผนงาน/รายชื่อคลิป.csv',data:new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'})});entries.push({name:'แผนงาน/สคริปต์เสียงพากย์.txt',data:new Blob([($('#voiceScriptText')?.value||state.voiceScript||'')],{type:'text/plain;charset=utf-8'})});entries.push({name:'อ่านก่อนใช้.txt',data:new Blob(['ชุดนี้คือคลิปต้นฉบับที่ AI เลือกและเรียงลำดับให้แล้ว\nไฟล์ยังไม่ถูกตัดช่วงหรือปรับสีลงในไฟล์จริง จึงสามารถนำไปตัดต่อใน Premiere, CapCut หรือโปรแกรมอื่นได้โดยไม่เสียคุณภาพ\nดูเวลาเริ่ม-จบที่แนะนำในไฟล์ แผนงาน/รายชื่อคลิป.csv'],{type:'text/plain;charset=utf-8'})});const zip=await makeStoreZip(entries);downloadBlob(zip,`tanjai-selected-footage-${new Date().toISOString().slice(0,10)}.zip`);TANJAI.toast(`ดาวน์โหลดคลิปที่เลือก ${entries.length-3} คลิปแล้ว`)}catch(err){console.error(err);TANJAI.toast('รวมไฟล์ไม่สำเร็จ ลองลดจำนวนคลิปหรือขนาดไฟล์')}finally{if(btn){btn.disabled=false;btn.textContent=old}}}

  function downloadPlan(){if(!state.analysis){TANJAI.toast('กรุณาวิเคราะห์ฟุตเทจก่อน');return;}const story=state.storyOptions[state.selectedStory];const data={app:'Tanjai AI Studio',version:'10.3.1',createdAt:new Date().toISOString(),context:{purpose:$('#editPurpose').value,tone:$('#editTone').value,details:$('#editContext').value,instruction:$('#editInstruction').value,aspect:$('#editAspect').value},analysis:state.analysis,story,voiceScript:$('#voiceScriptText').value,selectedClips:state.timeline.map((t,i)=>{const c=clipById(t.clipId);return{order:i+1,fileName:c?.name,category:c?.category,start:t.start,end:t.end,duration:t.duration,qualityScore:c?.score,reason:c?.reason,flags:c?.flags}})};downloadBlob(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),'tanjai-video-project-v10.3.1.json')}
  function downloadClipList(){if(!state.timeline.length){TANJAI.toast('ยังไม่มีคลิปที่เลือก');return;}const lines=['ลำดับ,ชื่อไฟล์,กลุ่ม,เริ่ม,จบ,คะแนน,เหตุผล',...state.timeline.map((t,i)=>{const c=clipById(t.clipId);return `${i+1},"${(c?.name||'').replace(/"/g,'""')}","${c?.category||''}",${t.start.toFixed(1)},${t.end.toFixed(1)},${c?.score||0},"${(c?.reason||'').replace(/"/g,'""')}"`})];downloadBlob(new Blob(['\ufeff'+lines.join('\n')],{type:'text/csv;charset=utf-8'}),'tanjai-selected-clips.csv')}
  function downloadBlob(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}

  document.addEventListener('DOMContentLoaded',install); TANJAI.videoEditorState=state;
})();
